type HeroOrbitProps = {
  size: number;
  rotation: number;
  orbitSpinDuration?: string;
  isOrbitSpin?: boolean;
  isSpin?: boolean;
  spinDuration?: string;
};

export const heroBGImage = [
  {
    id: 1,
    tag: "sparkle",
    orbitSize: 430,
    orbitRotation: -15,
    imgSize: 8,
    isOrbitSpin: true,
    orbitSpinDuration: "30s",
    isSpin: true,
    spinDuration: "5s",
  },
  {
    id: 2,
    tag: "sparkle",
    orbitSize: 490,
    orbitRotation: 75,
    imgSize: 5,
    isOrbitSpin: true,
    orbitSpinDuration: "32s",
    isSpin: true,
    spinDuration: "5s",
  },
  {
    id: 3,
    tag: "sparkle",
    orbitSize: 530,
    orbitRotation: 185,
    imgSize: 10,
    isOrbitSpin: true,
    orbitSpinDuration: "34s",
    isSpin: true,
    spinDuration: "5s",
  },
  {
    id: 4,
    tag: "circle",
    orbitSize: 520,
    orbitRotation: -41,
    imgSize: 3,
    isOrbitSpin: true,
    orbitSpinDuration: "36s",
    // isSpin: true,
    // spinDuration: "10s",
  },
  {
    id: 5,
    tag: "star",
    orbitSize: 550,
    orbitRotation: 20,
    imgSize: 12,
    isOrbitSpin: true,
    orbitSpinDuration: "38s",
    isSpin: true,
    spinDuration: "10s",
  },
  {
    id: 6,
    tag: "star",
    orbitSize: 620,
    orbitRotation: 98,
    imgSize: 8,
    isOrbitSpin: true,
    orbitSpinDuration: "40s",
    isSpin: true,
    spinDuration: "10s",
  },
  {
    id: 7,
    tag: "circle",
    orbitSize: 650,
    orbitRotation: -5,
    imgSize: 3,
    isOrbitSpin: true,
    orbitSpinDuration: "42s",
    // isSpin: true,
    // spinDuration: "10s",
  },
  {
    id: 8,
    tag: "sparkle",
    orbitSize: 710,
    orbitRotation: 144,
    imgSize: 14,
    isOrbitSpin: true,
    orbitSpinDuration: "44s",
    isSpin: true,
    spinDuration: "5s",
  },
  {
    id: 9,
    tag: "circle",
    orbitSize: 720,
    orbitRotation: 85,
    imgSize: 3,
    isOrbitSpin: true,
    orbitSpinDuration: "46s",
    // isSpin: true,
    // spinDuration: "10s",
  },
  {
    id: 10,
    tag: "star",
    orbitSize: 800,
    orbitRotation: -70,
    imgSize: 28,
    isOrbitSpin: true,
    orbitSpinDuration: "48s",
    isSpin: true,
    spinDuration: "10s",
  },
  // { id: 6, tag: "sparkle", orbitSize: 850, orbitRotation: -35, imgSize: 5 },
  // { id: 7, tag: "sparkle", orbitSize: 820, orbitRotation: 115, imgSize: 5 },
  // { id: 10, tag: "sparkle", orbitSize: 440, orbitRotation: -110, imgSize: 5 },
  // { id: 12, tag: "circle", orbitSize: 810, orbitRotation: 160, imgSize: 3 },
];
